config/routes.rb
Rails.application.routes.draw do
  resources :fisis

  resources :stocks

  resources :inventario_detalles

  resources :items

  resources :unidad_medidas

  resources :partidas

  resources :inventarios

  resources :almacens

  resources :det_venta

  get 'dd/ee'

  resources :det_pedidos

  resources :det_compras

  resources :compras

  resources :pedidos

  resources :categoria

  resources :proveedors

  resources :venta

  resources :clientes

  devise_for :users
  resources :productos

  
  get 'home/almacen'

  get 'home/caja'

  get 'home/contacto'

  get 'home/galeria'

  get 'home/index'

  get 'home/reportes'

  get 'home/servicios'

  
  root :to => 'home#index'

end

app/models/almacen.rb
class Almacen < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :user
  belongs_to :proveedor
  
end

app/models/det_compra.rb
class DetCompra < ActiveRecord::Base
  belongs_to :producto
  belongs_to :compra
end

app/models/det_pedido.rb
class DetPedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :producto
end

app/models/det_venta.rb
class DetVenta < ActiveRecord::Base
  belongs_to :venta
  belongs_to :producto
end

app/models/det_ventum.rb
class DetVentum < ActiveRecord::Base
  belongs_to :producto
  belongs_to :venta
end

app/models/fisi.rb
class Fisi < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  belongs_to :almacen
  before_create :adicionar_fecha
  before_save :adicionar_total
  before_save :actualizar_inventario
  before_destroy :marcar_destroy
  #after_destroy :actualizar_inventario

  # Relaciones
  has_many :inventario_detalles, :dependent => :destroy, :class_name => "InventarioDetalle"
  
  
  #default_scope :order =>"fecha DESC"

  # Nested Forms, son atrbutos detalle en un formulario, en este caso allow_destroy => true
  # hara que se borren todos los items relacionados
  accepts_nested_attributes_for :inventario_detalles, :allow_destroy => true#, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

 
  # validaciones
  validates_associated :almacen
  validates_presence_of :almacen_id


  # Atributos protegidos que no pueden ser modificados por los parametros
  #attr_protected :fecha, :total 
 
  # paginacion
  cattr_reader :per_page
  @@per_page = 9
  
  protected

  # Adiciona la fecha al registro
  def adicionar_fecha
    self.fecha = DateTime.now
  end

  # Metodo que calcula el total de los detalles en este caso (inventario_detalles) antes de salvar
  # Ver arriba accepts_nested_attributes_for
  def adicionar_total
    sum = 0
    inventario_detalles.each do |v|
      begin
        unless v.marked_for_destruction?
          sum += v.precio_unitario * v.cantidad
        end
      rescue
      end
    end
    self.total = sum
  end

  # Metodo que marca todos los items que deben ser eliminados
  # debido a que el maestro sera eliminado
  def marcar_destroy
    attrs = []
    inventario_detalles.each do |v|
      attrs << {:id => v.id,:_delete => true}
    end
    inventario_detalles_attributes = attrs
    actualizar_inventario
  end

  # metodo para poder actualizar el valor y el total que hay en inventarios
  def actualizar_inventario
    # Incio de una transaccion para poder asegurar que los datos
    # son almacenados correctamente
    inventario_detalles.each do |inv|
      # Este metodo de busqueda es creado automaticamente por Rails
      # a este tipo de metodos generados se llama metaprogramacion
      stock = Stock.find_by_almacen_id_and_item_id( almacen_id, inv.item_id )
      # Crear un stock vacio si retorna stock Nulo nil
      stock = Stock.new(:almacen_id => almacen_id, :cantidad => 0, :valor_inventario => 0) if stock.nil?
      # En este caso permite llamar a una funcion determinada de acurdo a la
      # operacion, permite que el codigo se mas claro
      case true
        when inv.marked_for_destruction?
          cantidad, valor =  actualizar_inventario_delete(inv, stock)
        when inv.new_record?
          cantidad, valor =  actualizar_inventario_create(inv, stock)
        else
          cantidad, valor = actualizar_inventario_update(inv, stock)
      end
      # Aqui es donde se crea el nuevo registro de stock
      Stock.create(:almacen_id => almacen_id, :valor_inventario => valor, :item_id => inv.item_id,
          :cantidad => cantidad, :activo => true, :estado => '' )
      # se marca como inactivo el ultimo
      stock.activo = false
      stock.save unless stock.id.nil?

    end

  end

protected
  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_delete(inv, stock)
    cantidad = stock.cantidad - inv.cantidad
    valor = stock.valor_inventario - inv.precio_unitario * inv.cantidad
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  # En este caso es necesario revisar en la base de datos cual es su estado actual ya que
  # el objeto inv es atualizado por los nuevos valores que ingresa el usuario
  def actualizar_inventario_update(inv, stock)
    # Valor que se encuentra almacenado en la Base de Datos
    db_inv = InventarioDetalle.find(inv.id)
    cantidad = inv.cantidad + stock.cantidad - db_inv.cantidad
    valor =  inv.cantidad * inv.precio_unitario + stock.valor_inventario - (db_inv.cantidad * db_inv.precio_unitario)
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_create(inv, stock)
    cantidad = stock.cantidad + inv.cantidad
    valor = stock.valor_inventario + inv.cantidad * inv.precio_unitario 
    [cantidad, valor]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :partida
  belongs_to :unidad_medida
end

app/models/partida.rb
class Partida < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :user
	belongs_to :categoria
	validates :nombre, presence: true,uniqueness: true
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :almacen
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :productos
   has_many :compras
   has_many :venta
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def almacen
  end

  def caja
  end

  def contacto
  end

  def galeria
  end

  def index
  end

  def reportes
  end

  def servicios
  end
end

app/helpers/dd_helper.rb
module DdHelper
end

app/helpers/fisis_helper.rb
module FisisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/almacen.html.erb
<div align="center">
  <table width="729" height="246" border="1">
    <tr>
      <td width="20" rowspan="4" bgcolor="#006699">&nbsp;</td>
      <td colspan="2" bgcolor="#FF99CC"><h1 align="center" class="Estilo1">ALMACEN</h1></td>
      <td width="20" rowspan="4" bgcolor="#006699">&nbsp;</td>
    </tr>
    <tr>
      <td width="295"><center><%=link_to image_tag('productos.jpg', :alt => 'Mos'), productos_path %></center> </td>
      <td width="320"><center><%=link_to image_tag('categorias.png', :alt => 'Mos'), categoria_path %></center> </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
	 <tr>
      <td colspan="2" bgcolor="#FF99CC">&nbsp;</td>
    </tr>
  </table>
</div>

app/views/home/caja.html.erb
<div align="center">
  <table width="746" height="500" border="5" bordercolor="#FF0000">
    <tr>
      <td width="8" rowspan="3" bgcolor="#FFCCFF">&nbsp;</td>
      <td height="68" colspan="4" bgcolor="#FFCCFF"><h1 align="center" class="Estilo1">Caja</h1></td>
      <td width="8" rowspan="3" bgcolor="#FFCCFF">&nbsp;</td>
    </tr>
    <tr>
      <td height="168" colspan="2" bgcolor="#99CCCC"><%=link_to image_tag('compras.png', :alt => 'Mos'), compras_path %></td>
      <td height="168" colspan="2" bgcolor="#CC99FF"><div align="center"><%=link_to image_tag('ventas.png', :alt => 'Mos'), venta_path %>	</div></td>
    </tr>
    
    
    <tr>
      <td width="262" height="252" bgcolor="#D9F0E2"><div align="center"></div></td>
      <td height="168" colspan="2" bgcolor="#999999"><div align="center"></div><%=link_to image_tag('inventario.png', :alt => 'Mos'), root_path %></td>
      <td width="216" bgcolor="#D5F0E2"><div align="center"></div></td>
    </tr>
  </table>
</div>

app/views/home/contacto.html.erb
<h1>SAJOMA S.A. CONTACTAME</h1>

		</div>
	  </div>
	</div>
   <!----End-header----->
	     
		 <!---start-content---->
		 <div class="wrap">
		 	<div class="about-desc">
		     <div class="content">	 	
		      <div class="about-data"> 
		       <h2>Ponerse en contacto</h2>
		          <div class="contact-form">
		          	<div class="left_form">
					     <form method="post" action="contact-post.html">
					    	<div>
						    	<span><label>Nombre</label></span>
						    	<span><input name="userName" type="text" class="textbox"></span>
						    </div>
						    <div>
						    	<span><label>E-mail</label></span>
						    	<span><input name="userEmail" type="text" class="textbox"></span>
						    </div>
						  </div>
					     <div class="right_form">
					        <div>					    	
						    	<span><label>Motivo</label></span>
						    	<span><textarea name="userMsg"> </textarea></span>
						    </div>
						   <div>
						   		<span><input type="submit" value="Submit" class="myButton"></span>
						   </div>
						 </div>
						  <div class="clear"></div>
					    </form>
				    </div>
				  <div class="content_bottom">
				 	<div class="company_address">
				     	<h2>Ubicacion</h2>
						    	<p>Calzada-Moyobamba,San Mrtin-Perú</p>
						   		<p>Jr.2 de Mayo S/N</p>
						   		<p>USA</p>
				   		<p>Telefono:(042) 526799</p>
				 	 	<p>Email: <span><a href="ericck-89@hotmail.com">ericck-89@hotmail.com</a></span></p>
				   		<p>Follow on: <span><a href="#">Facebook</a></span>, <span><a href="#">Twitter</a></span></p>
				     </div>
				       <div class="contact_info">
    	 				<h2>Encuentranos Aqui!!!</h2>
					    	  <div class="map">
							   	    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7935.426761806935!2d-77.06600806528097!3d-6.0340159013697106!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91b72451e0cc63ad%3A0xe98ee291aeb1a0f5!2sCalzada!5e0!3m2!1ses-419!2spe!4v1434030573118" width="600" height="450" frameborder="0" style="border:0"></iframe>
							  </div>
      				     </div>
				      <div class="clear"></div>
	                </div>
		 	  </div>
			</div>
			</div>
		  </div>		   			
		 <!---End-content---->
		  <!---start-footer---->
		  <div class="footer">
		    <div class="wrap">
			   	
			<div class="clear"> </div>
		</div>
	</div>
		 <!---End-footer---->

app/views/home/galeria.html.erb
<h1>SAJOMA S.A. GALERIA</h1>

<script src="js/jquery-1.10.2.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="js/jquery.easing.min.js"></script>
		<script type="text/javascript" src="js/jquery.mixitup.min.js"></script>
		<script type="text/javascript">
			$(function() {

				var filterList = {

					init : function() {

						// MixItUp plugin
						// http://mixitup.io
						$('#portfoliolist').mixitup({
							targetSelector : '.portfolio',
							filterSelector : '.filter',
							effects : ['fade'],
							easing : 'snap',
							// call the hover effect
							onMixEnd : filterList.hoverEffect()
						});

					},

					hoverEffect : function() {

						// Simple parallax effect
						$('#portfoliolist .portfolio').hover(function() {
							$(this).find('.label').stop().animate({
								bottom : 0
							}, 200, 'easeOutQuad');
							$(this).find('img').stop().animate({
								top : -30
							}, 500, 'easeOutQuad');
						}, function() {
							$(this).find('.label').stop().animate({
								bottom : -40
							}, 200, 'easeInQuad');
							$(this).find('img').stop().animate({
								top : 0
							}, 300, 'easeOutQuad');
						});

					}
				};

				// Run the show!
				filterList.init();

			});
		</script>

		</div>
	  </div>
	</div>
   
		 <div class="wrap">
		     <div class="content">	 	
		      <div class="about-data"> 
		       <h2>Nuestra galeria</h2>
                <p>lo Mejor de nuestra gente</p>		 	 
		 	   <div class="portfolio_main">
						<ul id="filters" class="clearfix">
							<li>
								<span class="filter active" data-filter="app card icon web">todos</span>
							</li>
							<li>
								<span class="filter" data-filter="app  icon">App</span>
							</li>
							<li>
								<span class="filter" data-filter="card ">Tarjeta</span>
							</li>
							<li>
								<span class="filter" data-filter="icon app card ">Icono</span>
							</li>
							<li>
								<span class="filter" data-filter="web card icon">Web</span>
							</li>
						</ul>
						<div id="portfoliolist">
							<div class="portfolio logo1" data-cat="logo">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s1.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Logo</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio app" data-cat="app">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s2.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">APP</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio web" data-cat="web">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s3.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Web design</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio card" data-cat="card">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s4.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Business card</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio app" data-cat="app">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s5.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">APP</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio card" data-cat="card">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s6.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Business card</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio card" data-cat="card">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s7.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Business card</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio logo1" data-cat="web">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s8.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Logo</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio app" data-cat="app">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s2.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">APP</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio card" data-cat="card">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s5.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Business card</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio logo1" data-cat="icon">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s1.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">Logo</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="portfolio logo1" data-cat="web">
								<div class="portfolio-wrapper">
									<div class="fancyDemo">
										<a rel="group" href="single.html"><img src="images/s5.jpg" alt=""class="img-responsive"/></a>
									</div>
									<div class="label">
										<div class="label-text">
											<span class="text-category">App</span>
										</div>
										<div class="label-bg"></div>
									</div>
								</div>
							</div>
							<div class="clear"></div>
						</div>
			       </div>
			    </div>
			 </div>
		  </div>		   			
		 <!---End-content---->
		 <!---start-footer---->
		  <div class="footer">
		    <div class="wrap">
			   
		   </div>
	     </div>
		 <!---End-footer---->

app/views/home/index.html.erb
<p class="text-success"><%=flash[:notice] %></p>

<h2><span>BIENVENIDOS!!! SAJOMA S.A. PRODUCTOS LACTEOS ECOALIMENTARIOS </span></h2><br>
                <h2>100% NATURAL</h2>
            </div>
             <div class="flexslider">
                  <ul class="slides">
                    <li><img src="images/slide1.jpg" alt="" /></li>
                    <li><img src="images/slide2.jpg" alt="" /></li>
                    <li><img src="images/slide3.jpg" alt="" /></li>
                   </ul>
                  <script type="text/javascript">
                    $(function(){
                      SyntaxHighlighter.all();
                    });
                    $(window).load(function(){
                      $('.flexslider').flexslider({
                        animation: "slide",
                        controlNav: false
                      });
                    });
                  </script>
                </div>

        </div>
      </div>
    </div>
   <!----End-header----->
           
         <!---start-content---->
         <div class="wrap">
           <div class="content">         
               <div class="top-grids">
                    <div class="section group">
                        <div class="grid_1_of_3 images_1_of_3 top_grid">
                            <div class="topgrid-desc">                           
                              <h3>Yogurt</h3>
                              <p>Contiene más de cien millones de bacterias vivas que presentan una gran cantidad de vitaminas del grupo B. Estas bacterias ayudan a combatir toda clase de infecciones en el sistema digestivo del cuerpo humano. </p>
                              </div>
                              <img src="images/grid-img1.jpg" alt="" />
                        </div>
                         <div class="grid_1_of_3 images_1_of_3 top_grid">
                             <div class="topgrid-desc">                          
                              <h3>Queso</h3>
                              <p>Este alimento es derivado de la leche. Por ello, es una importante fuente de calcio para el organismo. Prácticamente todos los beneficios del queso para la salud son posibles gracias a su rico contenido en calcio.</p>
                              </div>
                              <img src="images/grid-img2.jpg" alt="" />
                         </div>
                        <div class="grid_1_of_3 images_1_of_3 top_grid">
                             <div class="topgrid-desc">                          
                              <h3>Manjar</h3>
                              <p>Es un tipo de secreción de alto valor nutricional con una composición del 89% de agua. Contiene proteínas, lípidos y lactosa.Vitaminas Liposolubles: Vitamina A, provitamina D3, Vitamina D3, Vitamina E, K </p>
                              </div>
                           <img src="images/grid-img3.jpg" alt="" />
                        </div>
                    </div>
                </div>
                
              <div class="content-middle">
              <div class="content-middle-top">
                <h4>Fundo Sajoma!!! Centro Turistico Campestre</h4>
              </div>
               <div class="content-middle-desc">
                <div class="section group">
                <div class="lsidebar span_3_of_1">
                    <img src="images/grid-img.jpg" alt="" />
                 </div> 
                <div class="cont span_3_of_2">
                    <h3>Disfruta de la naturaleza</h3>
                    <p>Ven y pasa la e mejor experiencia de tu vida con la naturaleza y animales de garnja donde despejaras la mente junto a tu familia y amigo te ofrecemos hospedaje,comida,vivero y con un psicologo que le dara charlas para liberar la estres y vivir en felicidad </p>
                    <div class="more-info more-info2"><a href="#">Más</a></div>
                  </div>
                </div>
               </div>
              </div>
              
             <div class="content-bottom"> 
              <div class="section group">
                <div class="cont span_2_of_3">
                 <div class="services-desc-block">
                    <h3>Ganaderia</h3>
                    <p>Eent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes. Nulla dui. Fusce feugiat malesuada odio. </p>
                    <div class="more-info"><a href="#">Más</a></div>
                 </div>
                  <div class="services-desc-block">
                    <h3>Vivero</h3>
                    <p>Vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes. Nulla dui. Fusce feugiat malesuada odio. </p>
                    <div class="more-info"><a href="#">Más</a></div>
                 </div>
                </div>  
                <div class="rsidebar span_1_of_3">
                    <h3>Dejanos tu cometartio</h3>
                    <div class="news-letter">
                        <form method="post" action="contact-post.html">
                                <span><label>Nombre</label></span>
                                <span><input name="userName" type="text" class="textbox"></span>
                                <span><label>Email</label></span>
                                <span><input name="userEmail" type="text" class="textbox"></span>
                                <span><label>Mensaje</label></span>
                                <span><textarea name="userMsg"> </textarea></span>
                                <span><input type="submit" value="Enviar" ></span>
                         </form>
                     </div>
                 </div>         
               </div>
              </div>  

app/views/home/reportes.html.erb
<h1>Home#reportes</h1>
<p>Find me in app/views/home/reportes.html.erb</p>

app/views/home/servicios.html.erb
<div align="center">
  <table width="746" height="500" border="5" bordercolor="#FF0000">
    <tr>
      <td width="8" rowspan="3" bgcolor="#FFCCFF">&nbsp;</td>
      <td height="68" colspan="4" bgcolor="#FFCCFF"><h1 align="center" class="Estilo1">Mantenimiento</h1></td>
      <td width="8" rowspan="3" bgcolor="#FFCCFF">&nbsp;</td>
    </tr>
    <tr>
      <td height="168" colspan="2" bgcolor="#99CCCC"><%=link_to image_tag('trabajador.png', :alt => 'Mos'), root_path %></td>
      <td height="168" colspan="2" bgcolor="#CC99FF"><div align="center"><%=link_to image_tag('proveedor.png', :alt => 'Mos'), proveedors_path %></div></td>
    </tr>
    
    
    <tr>
      <td width="262" height="252" bgcolor="#D9F0E2"><div align="center"></div></td>
      <td height="168" colspan="2" bgcolor="#999999"><div align="center"></div><%=link_to image_tag('cliente.png', :alt => 'Mos'), clientes_path %></td>
      <td width="216" bgcolor="#D5F0E2"><div align="center"></div></td>
    </tr>
  </table>
</div>