config/routes.rb
Rails.application.routes.draw do
  resources :fisis

  resources :stocks

  resources :inventario_detalles

  resources :items

  resources :unidad_medidas

  resources :partidas

  resources :inventarios

  resources :almacens

  resources :det_venta

  get 'dd/ee'

  resources :det_pedidos

  resources :det_compras

  resources :compras

  resources :pedidos

  resources :categoria

  resources :proveedors

  resources :venta

  resources :clientes

  devise_for :users
  resources :productos

  
  get 'home/almacen'

  get 'home/caja'

  get 'home/contacto'

  get 'home/galeria'

  get 'home/index'

  get 'home/reportes'

  get 'home/servicios'

  
  root :to => 'home#index'

end

app/models/almacen.rb
class Almacen < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :user
  belongs_to :proveedor
  
end

app/models/det_compra.rb
class DetCompra < ActiveRecord::Base
  belongs_to :producto
  belongs_to :compra
end

app/models/det_pedido.rb
class DetPedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :producto
end

app/models/det_venta.rb
class DetVenta < ActiveRecord::Base
  belongs_to :venta
  belongs_to :producto
end

app/models/det_ventum.rb
class DetVentum < ActiveRecord::Base
  belongs_to :producto
  belongs_to :venta
end

app/models/fisi.rb
class Fisi < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  belongs_to :almacen
  before_create :adicionar_fecha
  before_save :adicionar_total
  before_save :actualizar_inventario
  before_destroy :marcar_destroy
  #after_destroy :actualizar_inventario

  # Relaciones
  has_many :inventario_detalles, :dependent => :destroy, :class_name => "InventarioDetalle"
  
  
  #default_scope :order =>"fecha DESC"

  # Nested Forms, son atrbutos detalle en un formulario, en este caso allow_destroy => true
  # hara que se borren todos los items relacionados
  accepts_nested_attributes_for :inventario_detalles, :allow_destroy => true#, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

 
  # validaciones
  validates_associated :almacen
  validates_presence_of :almacen_id


  # Atributos protegidos que no pueden ser modificados por los parametros
  #attr_protected :fecha, :total 
 
  # paginacion
  cattr_reader :per_page
  @@per_page = 9
  
  protected

  # Adiciona la fecha al registro
  def adicionar_fecha
    self.fecha = DateTime.now
  end

  # Metodo que calcula el total de los detalles en este caso (inventario_detalles) antes de salvar
  # Ver arriba accepts_nested_attributes_for
  def adicionar_total
    sum = 0
    inventario_detalles.each do |v|
      begin
        unless v.marked_for_destruction?
          sum += v.precio_unitario * v.cantidad
        end
      rescue
      end
    end
    self.total = sum
  end

  # Metodo que marca todos los items que deben ser eliminados
  # debido a que el maestro sera eliminado
  def marcar_destroy
    attrs = []
    inventario_detalles.each do |v|
      attrs << {:id => v.id,:_delete => true}
    end
    inventario_detalles_attributes = attrs
    actualizar_inventario
  end

  # metodo para poder actualizar el valor y el total que hay en inventarios
  def actualizar_inventario
    # Incio de una transaccion para poder asegurar que los datos
    # son almacenados correctamente
    inventario_detalles.each do |inv|
      # Este metodo de busqueda es creado automaticamente por Rails
      # a este tipo de metodos generados se llama metaprogramacion
      stock = Stock.find_by_almacen_id_and_item_id( almacen_id, inv.item_id )
      # Crear un stock vacio si retorna stock Nulo nil
      stock = Stock.new(:almacen_id => almacen_id, :cantidad => 0, :valor_inventario => 0) if stock.nil?
      # En este caso permite llamar a una funcion determinada de acurdo a la
      # operacion, permite que el codigo se mas claro
      case true
        when inv.marked_for_destruction?
          cantidad, valor =  actualizar_inventario_delete(inv, stock)
        when inv.new_record?
          cantidad, valor =  actualizar_inventario_create(inv, stock)
        else
          cantidad, valor = actualizar_inventario_update(inv, stock)
      end
      # Aqui es donde se crea el nuevo registro de stock
      Stock.create(:almacen_id => almacen_id, :valor_inventario => valor, :item_id => inv.item_id,
          :cantidad => cantidad, :activo => true, :estado => '' )
      # se marca como inactivo el ultimo
      stock.activo = false
      stock.save unless stock.id.nil?

    end

  end

protected
  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_delete(inv, stock)
    cantidad = stock.cantidad - inv.cantidad
    valor = stock.valor_inventario - inv.precio_unitario * inv.cantidad
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  # En este caso es necesario revisar en la base de datos cual es su estado actual ya que
  # el objeto inv es atualizado por los nuevos valores que ingresa el usuario
  def actualizar_inventario_update(inv, stock)
    # Valor que se encuentra almacenado en la Base de Datos
    db_inv = InventarioDetalle.find(inv.id)
    cantidad = inv.cantidad + stock.cantidad - db_inv.cantidad
    valor =  inv.cantidad * inv.precio_unitario + stock.valor_inventario - (db_inv.cantidad * db_inv.precio_unitario)
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_create(inv, stock)
    cantidad = stock.cantidad + inv.cantidad
    valor = stock.valor_inventario + inv.cantidad * inv.precio_unitario 
    [cantidad, valor]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :partida
  belongs_to :unidad_medida
end

app/models/partida.rb
class Partida < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :user
	belongs_to :categoria
	validates :nombre, presence: true,uniqueness: true
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :almacen
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :productos
   has_many :compras
   has_many :venta
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :user
end

app/controllers/det_pedidos_controller.rb
class DetPedidosController < ApplicationController
  before_action :set_det_pedido, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @det_pedidos = DetPedido.all
    respond_with(@det_pedidos)
  end

  def show
    respond_with(@det_pedido)
  end

  def new
    @det_pedido = DetPedido.new
    respond_with(@det_pedido)
  end

  def edit
  end

  def create
    @det_pedido = DetPedido.new(det_pedido_params)
    @det_pedido.save
    respond_with(@det_pedido)
  end

  def update
    @det_pedido.update(det_pedido_params)
    respond_with(@det_pedido)
  end

  def destroy
    @det_pedido.destroy
    respond_with(@det_pedido)
  end

  private
    def set_det_pedido
      @det_pedido = DetPedido.find(params[:id])
    end

    def det_pedido_params
      params.require(:det_pedido).permit(:pedido_id, :producto_id, :fecha, :cantidad, :precio)
    end
end

app/helpers/dd_helper.rb
module DdHelper
end

app/helpers/det_pedidos_helper.rb
module DetPedidosHelper
end

app/helpers/fisis_helper.rb
module FisisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/det_pedidos/_form.html.erb
<%= form_for(@det_pedido) do |f| %>
  <% if @det_pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@det_pedido.errors.count, "error") %> prohibited this det_pedido from being saved:</h2>

      <ul>
      <% @det_pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pedido_id %><br>
    <%= f.text_field :pedido_id %>
  </div>
  <div class="field">
    <%= f.label :producto_id %><br>
    <%= f.text_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/det_pedidos/edit.html.erb
<h1>Editing det_pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @det_pedido %> |
<%= link_to 'Back', det_pedidos_path %>

app/views/det_pedidos/index.html.erb
<h1>Listing det_pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Producto</th>
      <th>Fecha</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @det_pedidos.each do |det_pedido| %>
      <tr>
        <td><%= det_pedido.pedido %></td>
        <td><%= det_pedido.producto %></td>
        <td><%= det_pedido.fecha %></td>
        <td><%= det_pedido.cantidad %></td>
        <td><%= det_pedido.precio %></td>
        <td><%= link_to 'Show', det_pedido %></td>
        <td><%= link_to 'Edit', edit_det_pedido_path(det_pedido) %></td>
        <td><%= link_to 'Destroy', det_pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Det pedido', new_det_pedido_path %>

app/views/det_pedidos/new.html.erb
<h1>New det_pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', det_pedidos_path %>

app/views/det_pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @det_pedido.pedido %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @det_pedido.producto %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @det_pedido.fecha %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @det_pedido.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @det_pedido.precio %>
</p>

<%= link_to 'Edit', edit_det_pedido_path(@det_pedido) %> |
<%= link_to 'Back', det_pedidos_path %>