config/routes.rb
Rails.application.routes.draw do
  resources :fisis

  resources :stocks

  resources :inventario_detalles

  resources :items

  resources :unidad_medidas

  resources :partidas

  resources :inventarios

  resources :almacens

  resources :det_venta

  get 'dd/ee'

  resources :det_pedidos

  resources :det_compras

  resources :compras

  resources :pedidos

  resources :categoria

  resources :proveedors

  resources :venta

  resources :clientes

  devise_for :users
  resources :productos

  
  get 'home/almacen'

  get 'home/caja'

  get 'home/contacto'

  get 'home/galeria'

  get 'home/index'

  get 'home/reportes'

  get 'home/servicios'

  
  root :to => 'home#index'

end

app/models/almacen.rb
class Almacen < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :user
  belongs_to :proveedor
  
end

app/models/det_compra.rb
class DetCompra < ActiveRecord::Base
  belongs_to :producto
  belongs_to :compra
end

app/models/det_pedido.rb
class DetPedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :producto
end

app/models/det_venta.rb
class DetVenta < ActiveRecord::Base
  belongs_to :venta
  belongs_to :producto
end

app/models/det_ventum.rb
class DetVentum < ActiveRecord::Base
  belongs_to :producto
  belongs_to :venta
end

app/models/fisi.rb
class Fisi < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  belongs_to :almacen
  before_create :adicionar_fecha
  before_save :adicionar_total
  before_save :actualizar_inventario
  before_destroy :marcar_destroy
  #after_destroy :actualizar_inventario

  # Relaciones
  has_many :inventario_detalles, :dependent => :destroy, :class_name => "InventarioDetalle"
  
  
  #default_scope :order =>"fecha DESC"

  # Nested Forms, son atrbutos detalle en un formulario, en este caso allow_destroy => true
  # hara que se borren todos los items relacionados
  accepts_nested_attributes_for :inventario_detalles, :allow_destroy => true#, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

 
  # validaciones
  validates_associated :almacen
  validates_presence_of :almacen_id


  # Atributos protegidos que no pueden ser modificados por los parametros
  #attr_protected :fecha, :total 
 
  # paginacion
  cattr_reader :per_page
  @@per_page = 9
  
  protected

  # Adiciona la fecha al registro
  def adicionar_fecha
    self.fecha = DateTime.now
  end

  # Metodo que calcula el total de los detalles en este caso (inventario_detalles) antes de salvar
  # Ver arriba accepts_nested_attributes_for
  def adicionar_total
    sum = 0
    inventario_detalles.each do |v|
      begin
        unless v.marked_for_destruction?
          sum += v.precio_unitario * v.cantidad
        end
      rescue
      end
    end
    self.total = sum
  end

  # Metodo que marca todos los items que deben ser eliminados
  # debido a que el maestro sera eliminado
  def marcar_destroy
    attrs = []
    inventario_detalles.each do |v|
      attrs << {:id => v.id,:_delete => true}
    end
    inventario_detalles_attributes = attrs
    actualizar_inventario
  end

  # metodo para poder actualizar el valor y el total que hay en inventarios
  def actualizar_inventario
    # Incio de una transaccion para poder asegurar que los datos
    # son almacenados correctamente
    inventario_detalles.each do |inv|
      # Este metodo de busqueda es creado automaticamente por Rails
      # a este tipo de metodos generados se llama metaprogramacion
      stock = Stock.find_by_almacen_id_and_item_id( almacen_id, inv.item_id )
      # Crear un stock vacio si retorna stock Nulo nil
      stock = Stock.new(:almacen_id => almacen_id, :cantidad => 0, :valor_inventario => 0) if stock.nil?
      # En este caso permite llamar a una funcion determinada de acurdo a la
      # operacion, permite que el codigo se mas claro
      case true
        when inv.marked_for_destruction?
          cantidad, valor =  actualizar_inventario_delete(inv, stock)
        when inv.new_record?
          cantidad, valor =  actualizar_inventario_create(inv, stock)
        else
          cantidad, valor = actualizar_inventario_update(inv, stock)
      end
      # Aqui es donde se crea el nuevo registro de stock
      Stock.create(:almacen_id => almacen_id, :valor_inventario => valor, :item_id => inv.item_id,
          :cantidad => cantidad, :activo => true, :estado => '' )
      # se marca como inactivo el ultimo
      stock.activo = false
      stock.save unless stock.id.nil?

    end

  end

protected
  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_delete(inv, stock)
    cantidad = stock.cantidad - inv.cantidad
    valor = stock.valor_inventario - inv.precio_unitario * inv.cantidad
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  # En este caso es necesario revisar en la base de datos cual es su estado actual ya que
  # el objeto inv es atualizado por los nuevos valores que ingresa el usuario
  def actualizar_inventario_update(inv, stock)
    # Valor que se encuentra almacenado en la Base de Datos
    db_inv = InventarioDetalle.find(inv.id)
    cantidad = inv.cantidad + stock.cantidad - db_inv.cantidad
    valor =  inv.cantidad * inv.precio_unitario + stock.valor_inventario - (db_inv.cantidad * db_inv.precio_unitario)
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_create(inv, stock)
    cantidad = stock.cantidad + inv.cantidad
    valor = stock.valor_inventario + inv.cantidad * inv.precio_unitario 
    [cantidad, valor]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :partida
  belongs_to :unidad_medida
end

app/models/partida.rb
class Partida < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :user
	belongs_to :categoria
	validates :nombre, presence: true,uniqueness: true
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :almacen
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :productos
   has_many :compras
   has_many :venta
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :user
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @productos = Producto.all
    respond_with(@productos)
  end

  def show
    respond_with(@producto)
    
  end

  def new

    @producto = Producto.new
    respond_with(@producto)
  end

  def edit
  end

  def create
    @producto = current_user.productos.new(producto_params)
    @producto.save
    respond_with(@producto)
  end

  def update
    @producto.update(producto_params)
    respond_with(@producto)
  end

  def destroy
    @producto.destroy
    respond_with(@producto)
  end

  private
    def set_producto
      @producto = Producto.find(params[:id])
    end

    def producto_params
      params.require(:producto).permit(:nombre, :descripcion, :precio, :stock, :estado, :categoria_id)
    end
end

app/helpers/dd_helper.rb
module DdHelper
end

app/helpers/fisis_helper.rb
module FisisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
   <div class="field">
    <%== f.label :categoria %><br>
 <%=select("producto", "categoria_id", Categorium.all.collect {|p| [ p.nombre, p.id ] }, {prompt: 'Seleccione categoria'})%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th>Stock</th>
      <th>Estado</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.stock %></td>
        <td><%= producto.estado %></td>
        <td><%= producto.categoria_id %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= button_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @producto.estado %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria_id %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>