config/routes.rb
Rails.application.routes.draw do
  resources :fisis

  resources :stocks

  resources :inventario_detalles

  resources :items

  resources :unidad_medidas

  resources :partidas

  resources :inventarios

  resources :almacens

  resources :det_venta

  get 'dd/ee'

  resources :det_pedidos

  resources :det_compras

  resources :compras

  resources :pedidos

  resources :categoria

  resources :proveedors

  resources :venta

  resources :clientes

  devise_for :users
  resources :productos

  
  get 'home/almacen'

  get 'home/caja'

  get 'home/contacto'

  get 'home/galeria'

  get 'home/index'

  get 'home/reportes'

  get 'home/servicios'

  
  root :to => 'home#index'

end

app/models/almacen.rb
class Almacen < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :user
  belongs_to :proveedor
  
end

app/models/det_compra.rb
class DetCompra < ActiveRecord::Base
  belongs_to :producto
  belongs_to :compra
end

app/models/det_pedido.rb
class DetPedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :producto
end

app/models/det_venta.rb
class DetVenta < ActiveRecord::Base
  belongs_to :venta
  belongs_to :producto
end

app/models/det_ventum.rb
class DetVentum < ActiveRecord::Base
  belongs_to :producto
  belongs_to :venta
end

app/models/fisi.rb
class Fisi < ActiveRecord::Base
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  belongs_to :almacen
  before_create :adicionar_fecha
  before_save :adicionar_total
  before_save :actualizar_inventario
  before_destroy :marcar_destroy
  #after_destroy :actualizar_inventario

  # Relaciones
  has_many :inventario_detalles, :dependent => :destroy, :class_name => "InventarioDetalle"
  
  
  #default_scope :order =>"fecha DESC"

  # Nested Forms, son atrbutos detalle en un formulario, en este caso allow_destroy => true
  # hara que se borren todos los items relacionados
  accepts_nested_attributes_for :inventario_detalles, :allow_destroy => true#, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

 
  # validaciones
  validates_associated :almacen
  validates_presence_of :almacen_id


  # Atributos protegidos que no pueden ser modificados por los parametros
  #attr_protected :fecha, :total 
 
  # paginacion
  cattr_reader :per_page
  @@per_page = 9
  
  protected

  # Adiciona la fecha al registro
  def adicionar_fecha
    self.fecha = DateTime.now
  end

  # Metodo que calcula el total de los detalles en este caso (inventario_detalles) antes de salvar
  # Ver arriba accepts_nested_attributes_for
  def adicionar_total
    sum = 0
    inventario_detalles.each do |v|
      begin
        unless v.marked_for_destruction?
          sum += v.precio_unitario * v.cantidad
        end
      rescue
      end
    end
    self.total = sum
  end

  # Metodo que marca todos los items que deben ser eliminados
  # debido a que el maestro sera eliminado
  def marcar_destroy
    attrs = []
    inventario_detalles.each do |v|
      attrs << {:id => v.id,:_delete => true}
    end
    inventario_detalles_attributes = attrs
    actualizar_inventario
  end

  # metodo para poder actualizar el valor y el total que hay en inventarios
  def actualizar_inventario
    # Incio de una transaccion para poder asegurar que los datos
    # son almacenados correctamente
    inventario_detalles.each do |inv|
      # Este metodo de busqueda es creado automaticamente por Rails
      # a este tipo de metodos generados se llama metaprogramacion
      stock = Stock.find_by_almacen_id_and_item_id( almacen_id, inv.item_id )
      # Crear un stock vacio si retorna stock Nulo nil
      stock = Stock.new(:almacen_id => almacen_id, :cantidad => 0, :valor_inventario => 0) if stock.nil?
      # En este caso permite llamar a una funcion determinada de acurdo a la
      # operacion, permite que el codigo se mas claro
      case true
        when inv.marked_for_destruction?
          cantidad, valor =  actualizar_inventario_delete(inv, stock)
        when inv.new_record?
          cantidad, valor =  actualizar_inventario_create(inv, stock)
        else
          cantidad, valor = actualizar_inventario_update(inv, stock)
      end
      # Aqui es donde se crea el nuevo registro de stock
      Stock.create(:almacen_id => almacen_id, :valor_inventario => valor, :item_id => inv.item_id,
          :cantidad => cantidad, :activo => true, :estado => '' )
      # se marca como inactivo el ultimo
      stock.activo = false
      stock.save unless stock.id.nil?

    end

  end

protected
  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_delete(inv, stock)
    cantidad = stock.cantidad - inv.cantidad
    valor = stock.valor_inventario - inv.precio_unitario * inv.cantidad
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  # En este caso es necesario revisar en la base de datos cual es su estado actual ya que
  # el objeto inv es atualizado por los nuevos valores que ingresa el usuario
  def actualizar_inventario_update(inv, stock)
    # Valor que se encuentra almacenado en la Base de Datos
    db_inv = InventarioDetalle.find(inv.id)
    cantidad = inv.cantidad + stock.cantidad - db_inv.cantidad
    valor =  inv.cantidad * inv.precio_unitario + stock.valor_inventario - (db_inv.cantidad * db_inv.precio_unitario)
    [cantidad, valor]
  end

  # Funcion que realiza las operaciones par poder actualizar los totales dependiente de actualizar_inventario
  def actualizar_inventario_create(inv, stock)
    cantidad = stock.cantidad + inv.cantidad
    valor = stock.valor_inventario + inv.cantidad * inv.precio_unitario 
    [cantidad, valor]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :partida
  belongs_to :unidad_medida
end

app/models/partida.rb
class Partida < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :user
	belongs_to :categoria
	validates :nombre, presence: true,uniqueness: true
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :almacen
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :productos
   has_many :compras
   has_many :venta
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :user
end

app/controllers/almacens_controller.rb
class AlmacensController < ApplicationController
  before_action :set_almacen, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @almacens = Almacen.all
    respond_with(@almacens)
  end

  def show
    respond_with(@almacen)
  end

  def new
    @almacen = Almacen.new
    respond_with(@almacen)
  end

  def edit
  end

  def create
    @almacen = Almacen.new(almacen_params)
    @almacen.save
    respond_with(@almacen)
  end

  def update
    @almacen.update(almacen_params)
    respond_with(@almacen)
  end

  def destroy
    @almacen.destroy
    respond_with(@almacen)
  end

  private
    def set_almacen
      @almacen = Almacen.find(params[:id])
    end

    def almacen_params
      params.require(:almacen).permit(:nombre, :direccion, :codigo, :telefono)
    end
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/dd_helper.rb
module DdHelper
end

app/helpers/fisis_helper.rb
module FisisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/almacens/_form.html.erb
<%= form_for(@almacen) do |f| %>
  <% if @almacen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@almacen.errors.count, "error") %> prohibited this almacen from being saved:</h2>

      <ul>
      <% @almacen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/almacens/edit.html.erb
<h1>Editing almacen</h1>

<%= render 'form' %>

<%= link_to 'Ver', @almacen %> |
<%= link_to 'Atras', almacens_path %>

app/views/almacens/index.html.erb
<h1>Listing almacens</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Codigo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @almacens.each do |almacen| %>
      <tr>
        <td><%= almacen.nombre %></td>
        <td><%= almacen.direccion %></td>
        <td><%= almacen.codigo %></td>
        <td><%= almacen.telefono %></td>
        <td><%= link_to 'Show', almacen %></td>
        <td><%= link_to 'Edit', edit_almacen_path(almacen) %></td>
        <td><%= link_to 'Destroy', almacen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Almacen', new_almacen_path %>

app/views/almacens/new.html.erb
<h1>New almacen</h1>

<%= render 'form' %>

<%= link_to 'Back', almacens_path %>

app/views/almacens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @almacen.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @almacen.direccion %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @almacen.codigo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @almacen.telefono %>
</p>

<%= link_to 'Edit', edit_almacen_path(@almacen) %> |
<%= link_to 'Back', almacens_path %>